package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.Set;

/**
 * GoodsProduct generated by hbm2java
 */
public class GoodsProduct implements java.io.Serializable {

	private static final long serialVersionUID = 8049712884998602804L;

	/**
	 * 商品id
	 */
	private Integer gpId;
	/* 商品名称 */
	private String gpName;
	/* 商品介绍 */
	private String gpIntroduce;

	/* 商品原价 */
	private double gpOriginalPrice;

	/* 商品促销价格 */
	private double gpPromotePrice;

	/* 商品库存 */
	private int gpStock;

	/* 商品所属类别id 数据字典 */
	private int gpCid;

	/* 商品上传者用户id */
	private int gpUid;

	/* 商品创建时间 */
	private Date gpCreateDate;

	/* 商品封面图 */
	private String titleImg;

	private Set<GoodsProductimage> goodsProductimages;

	/**
	 * 商品平均星级
	 */
	private double gpStar;

	/**
	 * 商品状态 0下架 1上架 2审核中 3审核未通过 4删除
	 */
	private int gpStatus;

	public GoodsProduct() {
	}

	public GoodsProduct(String gpName, String gpIntroduce, double gpOriginalPrice, int gpStock, int gpCid, int gpUid,
			Date gpCreateDate, int gpStatus) {
		this.gpName = gpName;
		this.gpIntroduce = gpIntroduce;
		this.gpOriginalPrice = gpOriginalPrice;
		this.gpStock = gpStock;
		this.gpCid = gpCid;
		this.gpUid = gpUid;
		this.gpCreateDate = gpCreateDate;
		this.gpStatus = gpStatus;
	}

	public GoodsProduct(String gpName, String gpIntroduce, double gpOriginalPrice, double gpPromotePrice, int gpStock,
			int gpCid, int gpUid, Date gpCreateDate, int gpStatus) {
		this.gpName = gpName;
		this.gpIntroduce = gpIntroduce;
		this.gpOriginalPrice = gpOriginalPrice;
		this.gpPromotePrice = gpPromotePrice;
		this.gpStock = gpStock;
		this.gpCid = gpCid;
		this.gpUid = gpUid;
		this.gpCreateDate = gpCreateDate;
		this.gpStatus = gpStatus;
	}

	/**
	 * @return the gpId
	 */
	public Integer getGpId() {
		return gpId;
	}

	/**
	 * @param gpId the gpId to set
	 */
	public void setGpId(Integer gpId) {
		this.gpId = gpId;
	}

	/**
	 * @return the gpName
	 */
	public String getGpName() {
		return gpName;
	}

	/**
	 * @param gpName the gpName to set
	 */
	public void setGpName(String gpName) {
		this.gpName = gpName;
	}

	/**
	 * @return the gpIntroduce
	 */
	public String getGpIntroduce() {
		return gpIntroduce;
	}

	/**
	 * @param gpIntroduce the gpIntroduce to set
	 */
	public void setGpIntroduce(String gpIntroduce) {
		this.gpIntroduce = gpIntroduce;
	}

	/**
	 * @return the gpOriginalPrice
	 */
	public double getGpOriginalPrice() {
		return gpOriginalPrice;
	}

	/**
	 * @param gpOriginalPrice the gpOriginalPrice to set
	 */
	public void setGpOriginalPrice(double gpOriginalPrice) {
		this.gpOriginalPrice = gpOriginalPrice;
	}

	/**
	 * @return the gpPromotePrice
	 */
	public double getGpPromotePrice() {
		return gpPromotePrice;
	}

	/**
	 * @param gpPromotePrice the gpPromotePrice to set
	 */
	public void setGpPromotePrice(double gpPromotePrice) {
		this.gpPromotePrice = gpPromotePrice;
	}

	/**
	 * @return the gpStock
	 */
	public int getGpStock() {
		return gpStock;
	}

	/**
	 * @param gpStock the gpStock to set
	 */
	public void setGpStock(int gpStock) {
		this.gpStock = gpStock;
	}

	/**
	 * @return the gpCid
	 */
	public int getGpCid() {
		return gpCid;
	}

	/**
	 * @param gpCid the gpCid to set
	 */
	public void setGpCid(int gpCid) {
		this.gpCid = gpCid;
	}

	/**
	 * @return the gpUid
	 */
	public int getGpUid() {
		return gpUid;
	}

	/**
	 * @param gpUid the gpUid to set
	 */
	public void setGpUid(int gpUid) {
		this.gpUid = gpUid;
	}

	/**
	 * @return the gpCreateDate
	 */
	public Date getGpCreateDate() {
		return gpCreateDate;
	}

	/**
	 * @param gpCreateDate the gpCreateDate to set
	 */
	public void setGpCreateDate(Date gpCreateDate) {
		this.gpCreateDate = gpCreateDate;
	}

	/**
	 * @return the titleImg
	 */
	public String getTitleImg() {
		return titleImg;
	}

	/**
	 * @param titleImg the titleImg to set
	 */
	public void setTitleImg(String titleImg) {
		this.titleImg = titleImg;
	}

	/**
	 * @return the goodsProductimages
	 */
	public Set<GoodsProductimage> getGoodsProductimages() {
		return goodsProductimages;
	}

	/**
	 * @param goodsProductimages the goodsProductimages to set
	 */
	public void setGoodsProductimages(Set<GoodsProductimage> goodsProductimages) {
		this.goodsProductimages = goodsProductimages;
	}

	/**
	 * @return the gpStar
	 */
	public double getGpStar() {
		return gpStar;
	}

	/**
	 * @param gpStar the gpStar to set
	 */
	public void setGpStar(double gpStar) {
		this.gpStar = gpStar;
	}

	/**
	 * @return the gpStatus
	 */
	public int getGpStatus() {
		return gpStatus;
	}

	/**
	 * @param gpStatus the gpStatus to set
	 */
	public void setGpStatus(int gpStatus) {
		this.gpStatus = gpStatus;
	}

	@Override
	public String toString() {
		return "GoodsProduct{" + "gpId=" + gpId + ", gpName='" + gpName + '\'' + ", gpIntroduce='" + gpIntroduce + '\''
				+ ", gpOriginalPrice=" + gpOriginalPrice + ", gpPromotePrice=" + gpPromotePrice + ", gpStock=" + gpStock
				+ ", gpCid=" + gpCid + ", gpUid=" + gpUid + ", gpCreateDate=" + gpCreateDate + ", titleImg='" + titleImg
				+ '\'' + ", goodsProductimages=" + goodsProductimages + ", gpStar=" + gpStar + ", gpStatus=" + gpStatus
				+ '}';
	}
}
