package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsOrderitem generated by hbm2java
 */
public class GoodsOrderitem implements java.io.Serializable {

	private Integer goiId;
	private Integer goiPid; // 商品id
	private Integer goiOid; // 订单id
	private Integer goiUid; // 用户id
	private Integer goiNumber; // 商品数量
	private Integer goiStatus; // 订单商品状态 0交易关闭 1待付款2待发货（已付款） 3已发货（待收货）4已确认收货（待评论）5已评论
	private String goiNote; // 商品备注
	private int goiSid; // 卖家id
	private String goiPname; // 商品名称
	private String goiOrderCode; // 订单编号
	private double goiPrice; // 商品单价

	private GoodsProduct goodsProduct; // 商品 单向一对一

	public GoodsOrderitem() {
	}

	public GoodsOrderitem(Integer goiPid, Integer goiOid, Integer goiUid, Integer goiNumber, Integer goiStatus,
			String goiNote, int goiSid, String goiOrderCode, String goiPname, double goiPrice) {
		this.goiPid = goiPid;
		this.goiOid = goiOid;
		this.goiUid = goiUid;
		this.goiNumber = goiNumber;
		this.goiStatus = goiStatus;
		this.goiNote = goiNote;
		this.goiSid = goiSid;
		this.goiOrderCode = goiOrderCode;
		this.goiPname = goiPname;
		this.goiPrice = goiPrice;
	}

	public Integer getGoiId() {
		return this.goiId;
	}

	public void setGoiId(Integer goiId) {
		this.goiId = goiId;
	}

	public Integer getGoiPid() {
		return this.goiPid;
	}

	public void setGoiPid(Integer goiPid) {
		this.goiPid = goiPid;
	}

	public Integer getGoiOid() {
		return this.goiOid;
	}

	public void setGoiOid(Integer goiOid) {
		this.goiOid = goiOid;
	}

	public Integer getGoiUid() {
		return this.goiUid;
	}

	public void setGoiUid(Integer goiUid) {
		this.goiUid = goiUid;
	}

	public Integer getGoiNumber() {
		return this.goiNumber;
	}

	public void setGoiNumber(Integer goiNumber) {
		this.goiNumber = goiNumber;
	}

	public Integer getGoiStatus() {
		return this.goiStatus;
	}

	public void setGoiStatus(Integer goiStatus) {
		this.goiStatus = goiStatus;
	}

	/**
	 * @return the goiNote
	 */
	public String getGoiNote() {
		return goiNote;
	}

	/**
	 * @param goiNote the goiNote to set
	 */
	public void setGoiNote(String goiNote) {
		this.goiNote = goiNote;
	}

	/**
	 * @return the goiSid
	 */
	public int getGoiSid() {
		return goiSid;
	}

	/**
	 * @param goiSid the goiSid to set
	 */
	public void setGoiSid(int goiSid) {
		this.goiSid = goiSid;
	}

	/**
	 * @return the goiPname
	 */
	public String getGoiPname() {
		return goiPname;
	}

	/**
	 * @param goiPname the goiPname to set
	 */
	public void setGoiPname(String goiPname) {
		this.goiPname = goiPname;
	}

	public String getGoiOrderCode() {
		return goiOrderCode;
	}

	public void setGoiOrderCode(String goiOrderCode) {
		this.goiOrderCode = goiOrderCode;
	}

	public double getGoiPrice() {
		return goiPrice;
	}

	public void setGoiPrice(double goiPrice) {
		this.goiPrice = goiPrice;
	}

	public GoodsProduct getGoodsProduct() {
		return goodsProduct;
	}

	public void setGoodsProduct(GoodsProduct goodsProduct) {
		this.goodsProduct = goodsProduct;
	}

	@Override
	public String toString() {
		return "GoodsOrderitem{" + "goiId=" + goiId + ", goiPid=" + goiPid + ", goiOid=" + goiOid + ", goiUid=" + goiUid
				+ ", goiNumber=" + goiNumber + ", goiStatus=" + goiStatus + ", goiNote='" + goiNote + '\'' + ", goiSid="
				+ goiSid + ", goiPname='" + goiPname + '\'' + ", goiOrderCode='" + goiOrderCode + '\'' + ", goiPrice="
				+ goiPrice + ", goodsProduct=" + goodsProduct + '}';
	}
}
