package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsUser generated by hbm2java
 */
public class GoodsUser implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// 对应表的gu_id
	private int guId;
	// 对应表的gu_name
	private String guName;
	// 对应表的gu_password
	private String guPassword;
	// 对应表的gu_status
	private int guStatus;
	// 对应表的gu_sex
	private String guSex;
	// 对应表的gu_age
	private Integer guAge;
	// 对应表的gu_phone
	private String guPhone;
	// 对应表的gu_address
	private String guAddress;
	// 对应表的gu_email
	private String guEmail;
	@Override
	public String toString() {
		return "GoodsUser [guId=" + guId + ", guName=" + guName + ", guPassword=" + guPassword + ", guStatus="
				+ guStatus + ", guSex=" + guSex + ", guAge=" + guAge + ", guPhone=" + guPhone + ", guAddress="
				+ guAddress + ", guEmail=" + guEmail + "]";
	}
	public GoodsUser() {
		super();
	}
	public GoodsUser(int guId, String guName, String guPassword, int guStatus, String guSex, Integer guAge,
			String guPhone, String guAddress, String guEmail) {
		super();
		this.guId = guId;
		this.guName = guName;
		this.guPassword = guPassword;
		this.guStatus = guStatus;
		this.guSex = guSex;
		this.guAge = guAge;
		this.guPhone = guPhone;
		this.guAddress = guAddress;
		this.guEmail = guEmail;

	}

	public int getGuId() {
		return guId;
	}

	public void setGuId(int guId) {
		this.guId = guId;
	}

	public String getGuName() {
		return guName;
	}

	public void setGuName(String guName) {
		this.guName = guName;
	}

	public String getGuPassword() {
		return guPassword;
	}

	public void setGuPassword(String guPassword) {
		this.guPassword = guPassword;
	}

	public int getGuStatus() {
		return guStatus;
	}

	public void setGuStatus(int guStatus) {
		this.guStatus = guStatus;
	}

	public String getGuSex() {
		return guSex;
	}

	public void setGuSex(String guSex) {
		this.guSex = guSex;
	}

	public Integer getGuAge() {
		return guAge;
	}

	public void setGuAge(Integer guAge) {
		this.guAge = guAge;
	}

	public String getGuPhone() {
		return guPhone;
	}

	public void setGuPhone(String guPhone) {
		this.guPhone = guPhone;
	}

	public String getGuAddress() {
		return guAddress;
	}

	public void setGuAddress(String guAddress) {
		this.guAddress = guAddress;
	}

	public String getGuEmail() {
		return guEmail;
	}

	public void setGuEmail(String guEmail) {
		this.guEmail = guEmail;
	}

}
