package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsCategory generated by hbm2java
 */
public class GoodsCategory implements java.io.Serializable {

	private Integer gcId;
	private String gcName;
	private int gcStatus;

	public GoodsCategory() {
	}

	public GoodsCategory(String gcName, int gcStatus) {
		this.gcName = gcName;
		this.gcStatus = gcStatus;
	}

	public Integer getGcId() {
		return this.gcId;
	}

	public void setGcId(Integer gcId) {
		this.gcId = gcId;
	}

	public String getGcName() {
		return this.gcName;
	}

	public void setGcName(String gcName) {
		this.gcName = gcName;
	}

	public int getGcStatus() {
		return this.gcStatus;
	}

	public void setGcStatus(int gcStatus) {
		this.gcStatus = gcStatus;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "GoodsCategory [gcId=" + gcId + ", gcName=" + gcName + ", gcStatus=" + gcStatus + "]";
	}

}
