package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.Set;

/**
 * GoodsOrder generated by hbm2java
 */
public class GoodsOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer goId;
	private String goOrderCode;
	private String goAddress;
	private String goReceiver;
	private String goPhone;
	private double goTotalPrice;
	private Date goCreateDate;
	private Date goPayDate;
	private Date goDeliveryDate;
	private Date goConfirmDate;
	private int goUid;                    //买家id
	private int goStatus;
	private int goSid;// 卖家ID
	private String goSname;// 卖家名称

	private Set<GoodsOrderitem> goodsOrderitemSet; // 订单包含的商品集合

	/**
	 * @return the goId
	 */
	public Integer getGoId() {
		return goId;
	}

	/**
	 * @param goId the goId to set
	 */
	public void setGoId(Integer goId) {
		this.goId = goId;
	}

	/**
	 * @return the goOrderCode
	 */
	public String getGoOrderCode() {
		return goOrderCode;
	}

	/**
	 * @param goOrderCode the goOrderCode to set
	 */
	public void setGoOrderCode(String goOrderCode) {
		this.goOrderCode = goOrderCode;
	}

	/**
	 * @return the goAddress
	 */
	public String getGoAddress() {
		return goAddress;
	}

	/**
	 * @param goAddress the goAddress to set
	 */
	public void setGoAddress(String goAddress) {
		this.goAddress = goAddress;
	}

	/**
	 * @return the goReceiver
	 */
	public String getGoReceiver() {
		return goReceiver;
	}

	/**
	 * @param goReceiver the goReceiver to set
	 */
	public void setGoReceiver(String goReceiver) {
		this.goReceiver = goReceiver;
	}

	/**
	 * @return the goPhone
	 */
	public String getGoPhone() {
		return goPhone;
	}

	/**
	 * @param goPhone the goPhone to set
	 */
	public void setGoPhone(String goPhone) {
		this.goPhone = goPhone;
	}

	/**
	 * @return the goTotalPrice
	 */
	public double getGoTotalPrice() {
		return goTotalPrice;
	}

	/**
	 * @param goTotalPrice the goTotalPrice to set
	 */
	public void setGoTotalPrice(double goTotalPrice) {
		this.goTotalPrice = goTotalPrice;
	}

	/**
	 * @return the goCreateDate
	 */
	public Date getGoCreateDate() {
		return goCreateDate;
	}

	/**
	 * @param goCreateDate the goCreateDate to set
	 */
	public void setGoCreateDate(Date goCreateDate) {
		this.goCreateDate = goCreateDate;
	}

	/**
	 * @return the goPayDate
	 */
	public Date getGoPayDate() {
		return goPayDate;
	}

	/**
	 * @param goPayDate the goPayDate to set
	 */
	public void setGoPayDate(Date goPayDate) {
		this.goPayDate = goPayDate;
	}

	/**
	 * @return the goDeliveryDate
	 */
	public Date getGoDeliveryDate() {
		return goDeliveryDate;
	}

	/**
	 * @param goDeliveryDate the goDeliveryDate to set
	 */
	public void setGoDeliveryDate(Date goDeliveryDate) {
		this.goDeliveryDate = goDeliveryDate;
	}

	/**
	 * @return the goConfirmDate
	 */
	public Date getGoConfirmDate() {
		return goConfirmDate;
	}

	/**
	 * @param goConfirmDate the goConfirmDate to set
	 */
	public void setGoConfirmDate(Date goConfirmDate) {
		this.goConfirmDate = goConfirmDate;
	}

	/**
	 * @return the goUid
	 */
	public int getGoUid() {
		return goUid;
	}

	/**
	 * @param goUid the goUid to set
	 */
	public void setGoUid(int goUid) {
		this.goUid = goUid;
	}

	/**
	 * @return the goStatus
	 */
	public int getGoStatus() {
		return goStatus;
	}

	/**
	 * @param goStatus the goStatus to set
	 */
	public void setGoStatus(int goStatus) {
		this.goStatus = goStatus;
	}

	/**
	 * @return the goSid
	 */
	public int getGoSid() {
		return goSid;
	}

	/**
	 * @param goSid the goSid to set
	 */
	public void setGoSid(int goSid) {
		this.goSid = goSid;
	}

	/**
	 * @return the goSname
	 */
	public String getGoSname() {
		return goSname;
	}

	/**
	 * @param goSname the goSname to set
	 */
	public void setGoSname(String goSname) {
		this.goSname = goSname;
	}

	public Set<GoodsOrderitem> getGoodsOrderitemSet() {
		return goodsOrderitemSet;
	}

	public void setGoodsOrderitemSet(Set<GoodsOrderitem> goodsOrderitemSet) {
		this.goodsOrderitemSet = goodsOrderitemSet;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "GoodsOrder{" + "goId=" + goId + ", goOrderCode='" + goOrderCode + '\'' + ", goAddress='" + goAddress
				+ '\'' + ", goReceiver='" + goReceiver + '\'' + ", goPhone='" + goPhone + '\'' + ", goTotalPrice="
				+ goTotalPrice + ", goCreateDate=" + goCreateDate + ", goPayDate=" + goPayDate + ", goDeliveryDate="
				+ goDeliveryDate + ", goConfirmDate=" + goConfirmDate + ", goUid=" + goUid + ", goStatus=" + goStatus
				+ ", goodsOrderitemSet=" + goodsOrderitemSet + ", goSid=" + goSid + ", goSname='" + goSname + '\''
				+ '}';
	}
}
