package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsUserId generated by hbm2java
 */
public class GoodsUserId implements java.io.Serializable {

	private int guId;
	private String guName;

	public GoodsUserId() {
	}

	public GoodsUserId(int guId, String guName) {
		this.guId = guId;
		this.guName = guName;
	}

	public int getGuId() {
		return this.guId;
	}

	public void setGuId(int guId) {
		this.guId = guId;
	}

	public String getGuName() {
		return this.guName;
	}

	public void setGuName(String guName) {
		this.guName = guName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GoodsUserId))
			return false;
		GoodsUserId castOther = (GoodsUserId) other;

		return (this.getGuId() == castOther.getGuId())
				&& ((this.getGuName() == castOther.getGuName()) || (this.getGuName() != null
						&& castOther.getGuName() != null && this.getGuName().equals(castOther.getGuName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGuId();
		result = 37 * result + (getGuName() == null ? 0 : this.getGuName().hashCode());
		return result;
	}

}
