package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsProductimage generated by hbm2java
 */
public class GoodsProductimage implements java.io.Serializable {

	private Integer gpiId;

	private int gpiPid;
	private String gpiType;
	private String gpiUrl;
	private int gpiStatus;

	public GoodsProductimage() {
	}

	
	public GoodsProductimage(int gpiPid, String gpiType, String gpiUrl, int gpiStatus) {
		super();
		this.gpiPid = gpiPid;
		this.gpiType = gpiType;
		this.gpiUrl = gpiUrl;
		this.gpiStatus = gpiStatus;
	}




	public String getGpiUrl() {
		return gpiUrl;
	}


	public void setGpiUrl(String gpiUrl) {
		this.gpiUrl = gpiUrl;
	}


	public Integer getGpiId() {
		return this.gpiId;
	}

	public void setGpiId(Integer gpiId) {
		this.gpiId = gpiId;
	}

	public int getGpiPid() {
		return this.gpiPid;
	}

	public void setGpiPid(int gpiPid) {
		this.gpiPid = gpiPid;
	}

	public String getGpiType() {
		return this.gpiType;
	}

	public void setGpiType(String gpiType) {
		this.gpiType = gpiType;
	}

	public int getGpiStatus() {
		return this.gpiStatus;
	}

	public void setGpiStatus(int gpiStatus) {
		this.gpiStatus = gpiStatus;
	}


	@Override
	public String toString() {
		return "GoodsProductimage{" +
				"gpiId=" + gpiId +
				", gpiPid=" + gpiPid +
				", gpiType='" + gpiType + '\'' +
				", gpiUrl='" + gpiUrl + '\'' +
				", gpiStatus=" + gpiStatus +
				'}';
	}

}
