package com.qst.pojo;
// Generated 2019-8-6 21:46:28 by Hibernate Tools 5.2.3.Final

/**
 * GoodsAdmin generated by hbm2java
 */
@SuppressWarnings("serial")
public class GoodsAdmin implements java.io.Serializable {
	/** 管理员Id */
	private int gaId;
	/** 管理员名字 */
	private String gaName;
	/** 管理员密码 */
	private String gaPassword;
	/** 管理员权限 1普通管理员 9超级管理员 */
	private int gaRank;
	/** 管理员状态 0 禁用 1启用 2删除 */
	private int gaStatus;

	public GoodsAdmin() {
	}

	public GoodsAdmin(String gaName, String gaPassword, int gaRank, int gaStatus) {
		super();
		this.gaName = gaName;
		this.gaPassword = gaPassword;
		this.gaRank = gaRank;
		this.gaStatus = gaStatus;
	}

	public int getGaId() {
		return gaId;
	}

	public void setGaId(int gaId) {
		this.gaId = gaId;
	}

	public String getGaName() {
		return gaName;
	}

	public void setGaName(String gaName) {
		this.gaName = gaName;
	}

	public String getGaPassword() {
		return this.gaPassword;
	}

	public void setGaPassword(String gaPassword) {
		this.gaPassword = gaPassword;
	}

	public int getGaRank() {
		return this.gaRank;
	}

	public void setGaRank(int gaRank) {
		this.gaRank = gaRank;
	}

	public int getGaStatus() {
		return this.gaStatus;
	}

	public void setGaStatus(int gaStatus) {
		this.gaStatus = gaStatus;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "GoodsAdmin [gaId=" + gaId + ", gaName=" + gaName + ", gaPassword=" + gaPassword + ", gaRank=" + gaRank
				+ ", gaStatus=" + gaStatus + "]";
	}

}
